#!/bin/bash

# Main repo
cd ~/storage/shared/obsidian || exit
git add .
git commit -a -m "Android vault backup: $(date +'%Y-%m-%d %H:%M:%S')"
git pull --no-ff
git push

# Settings
cd .obsidian || exit
git add .
git commit -a -m "Android obsidian settings backup: $(date +'%Y-%m-%d %H:%M:%S')"
git pull --no-ff
git push
