#!/bin/bash

install_apt_packages() {
  sudo apt-get update
  sudo apt-get install -y \
    zsh \
    git \
    curl \
    vim \
    htop \
    tree \
    gparted \
    make \
    libfuse2 \
    neofetch
}

setup_zsh() {
  zsh zap_zsh_install  # minimal zsh plugin manager
  sudo chsh -s $(which zsh) $USER # set zsh as default shell

  # fuzzy finder
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  ~/.fzf/install
}

install_apt_packages
setup_zsh
