#!/bin/bash

install_apt_packages() {
  sudo apt-get update
  sudo apt-get install -y \
  zsh \
  git \
  curl \
  vim \
  htop \
  nvtop \
  iftop \
  tree \
  gparted \
  make \
  libfuse2 \
  neofetch
}

setup_zsh() {
  zsh zap_zsh_install             # minimal zsh plugin manager
  sudo chsh -s $(which zsh) $USER # set zsh as default shell

  # fuzzy finder
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  ~/.fzf/install
}

install_theme() {
  curl -sSL "https://github.com/zthxxx/jovial/raw/master/jovial.zsh-theme" -o ~/jovial.zsh-theme
}

echo "Installing apt packages..."
install_apt_packages
echo "Setting up zsh..."
setup_zsh
echo "Installing theme..."
install_theme
