#!/bin/bash

install_apt_packages() {
  sudo apt-get update
  sudo apt-get install -y \
    curl \
    git \
    gparted \
    htop \
    iftop \
    libfuse2 \
    lm-sensors \
    make \
    neofetch \
    nvtop \
    ssh \
    tree \
    zathura \
    zsh \
    gnome-shell-extensions-gpaste \
    pulseaudio-module-bluetooth \
    blueman \
    python3 \
    python3-pip \
    baobab \
    ripgrep
}

remove_apt_packages() {
    # screen reader
    sudo apt-get remove -y orca
    # braille display driver
    sudo apt-get remove -y brltty
}

setup_zsh() {
  zsh zsh/plugin-files/zap_zsh_install # minimal zsh plugin manager
  sudo chsh -s "$(which zsh)" "$USER" # set zsh as default shell
}

install_theme() {
  curl -sSL "https://github.com/zthxxx/jovial/raw/master/jovial.zsh-theme" -o zsh/plugin-files/mytheme.zsh-theme
  pip3 install --usesr pywal
}

install_fzf() {
  # fuzzy finder
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  ~/.fzf/install
}

disable_screenshot_sound() {
    if [ -f "/usr/share/sounds/freedesktop/stereo/camera-shutter.oga" ]; then
        sudo mv /usr/share/sounds/freedesktop/stereo/camera-shutter.oga /usr/share/sounds/freedesktop/stereo/camera-shutter-disabled.oga
    fi
}

install_vim_9() {
    sudo add-apt-repository ppa:jonathonf/vim -y
    sudo apt install --reinstall vim -y
}

install_nodejs() {
    sudo apt-get update &&  sudo apt-get install -y ca-certificates curl gnupg
    sudo mkdir -p /etc/apt/keyrings
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
    NODE_MAJOR=21
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
    sudo apt-get update && sudo apt-get install nodejs -y
}

echo "Setting ssh folder permissions..."
./bin/ssheperm
echo "Installing vim 9..."
install_vim_9
echo "Installing nodejs..."
install_nodejs
echo "Installing apt packages..."
install_apt_packages
echo "Setting up zsh..."
setup_zsh
echo "Installing fzf..."
install_fzf
echo "Installing theme..."
install_theme
echo "Disabling screenshot sound..."
disable_screenshot_sound
echo "Importing keybindings..."
./bin/keybindings.pl -i
echo "Removing bloat.."
remove_apt_packages
echo "Symlinking scripts from ~/bin to /usr/local/bin..."
sudo mkdir -p /usr/local/bin
sudo ln -s ~/bin/* /usr/local/bin/
