" line numbers https://linuxize.com/post/how-to-show-line-numbers-in-vim/
set number
set relativenumber
" Disable bell on esc (also no visual blinking...)
set noerrorbells visualbell t_vb=

" https://stackoverflow.com/a/234578/17777085
filetype plugin indent on
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab

" Uses H and L To navigate between blank lines in Visual and Normal modes.
noremap H {
noremap L }

" Uses K and J to scroll back and forth in Visual and Normal modes
noremap K <C-b>
noremap J <C-f>


call plug#begin('~/.vim/plugged')

" TODO change Ctrl+n to alt+j https://www.reddit.com/r/neovim/comments/17dcy9i/plugin_or_command_for_simultaneous_nonadjacent/
Plug 'mg979/vim-visual-multi', {'branch': 'master'}

call plug#end()

