# Home Manager for `agent@pc` -- the user dispatch workers run as. Deliberately
# not an import of common.nix: that file is max's environment, down to his git
# identity, his ssh hosts and symlinks into ~/.dotfiles, none of which exist or
# belong here. This user starts from nothing and gets only what a worker needs.
{ config, osConfig, pkgs, lib, ... }:

let
  # The one list: installed as packages and named in HOST.md below, so the
  # record dispatch reads cannot drift from what is actually here.
  toolchain = with pkgs; [
    ast-grep
    chromium
    curl
    fd
    gh
    git
    gnumake
    jq
    nodejs
    ripgrep
    rsync
    tmux
    uv
    xvfb-run
  ];
in
{
  home.username = "agent";
  home.homeDirectory = "/home/agent";
  home.stateVersion = "26.05";

  targets.genericLinux.enable = false;

  home.packages = toolchain;

  # The claude native installer puts its binary here, and cannot add it to PATH
  # itself: home-manager owns .zshrc as a read-only store symlink.
  home.sessionPath = [ "${config.home.homeDirectory}/.local/bin" ];

  # Points at this user's own rootless daemon. Set per-user rather than through
  # `virtualisation.docker.rootless.setSocketVariable`, which would export it
  # for max too -- see nix/nixos/pc/agent-user.nix.
  home.sessionVariables.DOCKER_HOST =
    "unix:///run/user/${toString osConfig.users.users.agent.uid}/docker.sock";

  # Minimal on purpose: `ssh agent@pc <cmd>` runs a non-login zsh, which reads
  # .zshenv and nothing else -- that is where home-manager puts the session
  # variables and PATH above.
  programs.zsh.enable = true;

  programs.git = {
    enable = true;
    settings = {
      # Worker commits are attributable in `git log` as the bot account, not as
      # max. There is no GitHub credential here; this is identity, not access.
      user.name = "MaxWolf-01-clanker";
      user.email = "MaxWolf-01-clanker@users.noreply.github.com";
      init.defaultBranch = "master";
      push.default = "current";
      pull.rebase = false;
    };
  };

  # No resurrect, no clipboard integration: worker sessions are ephemeral and
  # this machine is headless. Just enough that attaching to watch a worker
  # feels like max's own tmux.
  programs.tmux = {
    enable = true;
    prefix = "C-a";
    escapeTime = 0;
    historyLimit = 50000;
    baseIndex = 1;
    mouse = true;
    keyMode = "vi";
    extraConfig = ''
      set -g default-terminal "tmux-256color"
      set -g renumber-windows on
      set -g status-style "bg=colour235,fg=colour250"
      set -g status-left "#[fg=colour117,bold] #S #[fg=colour244]| "
    '';
  };

  # What dispatch reads before planning a wave. The toolchain list is generated
  # from the packages above, so that half cannot drift; the limits below are
  # claims about this host, and every one of them has been exercised.
  home.file."HOST.md".text = ''
    ---
    host: pc
    user: agent
    isolated: true
    ---

    # Worker host: agent@pc

    Dispatch workers run here as `agent`, an unprivileged user with no path to
    max's data, the system config, or the tailnet. Generated by that user's
    Home Manager config (`nix/home/hosts/pc-agent.nix` in ~/.dotfiles).

    ## Toolchain

    ${lib.concatMapStringsSep "\n" (p: "- `${lib.getName p}`") toolchain}

    Plus `nix` (flakes enabled, untrusted user), rootless `docker`, and
    `claude` with the `mx` plugin. Anything a project needs beyond this comes
    from its own setup target, inside the worktree.

    ## Limits

    Each of these is a **blocker to report**, never a task to work around:

    - No `sudo`, no root, no system-wide installs. A missing system dependency
      is a blocker.
    - No GitHub credentials. `gh` is unauthenticated, private dependencies do
      not resolve, and nothing here can push to GitHub or open a PR — history
      arrives by push from the orchestrator and leaves the same way.
    - No access to max's home or the storage pool on this machine.
    - No tailnet. Other tailnet nodes are unreachable from this user; the
      public internet is not affected. Containers inherit the block, which is
      drawn by uid rather than by interface.
    - The GPU is visible here, but it is not yours: dispatch work runs no
      training and no CUDA jobs on this machine, which has its own GPU workers.
      A ticket that needs the GPU is a blocker.
    - Headless browsing only — `chromium --headless`, or under `xvfb-run`. No
      interactive browser driving.
    - Rootless docker: containers run inside this user's namespace, so
      `--privileged` and `--network host` are accepted but grant nothing beyond
      what this user already has. No GPU passthrough.
  '';
}
