# Home Manager for `agent@pc` -- the user dispatch workers run as. Deliberately
# not an import of common.nix: that file is max's environment, down to his git
# identity, his ssh hosts and symlinks into ~/.dotfiles, none of which exist or
# belong here. This user starts from nothing and gets only what a worker needs.
{ config, osConfig, pkgs, lib, ... }:

let
  # The one list: installed as packages and named in HOST.md below, so the
  # record dispatch reads cannot drift from what is actually here. It is
  # rendered there by mainProgram, because a worker looks for `make` and `rg`,
  # not for `gnumake` and `ripgrep`. A package that declares no mainProgram
  # fails evaluation rather than falling back to its package name -- the record
  # naming a command that does not exist is the failure worth being loud about.
  toolchain = with pkgs; [
    ast-grep
    chromium
    curl
    fd
    gh
    git
    gnumake
    jq
    nodejs
    ripgrep
    rsync
    tmux
    uv
    xvfb-run
  ];
in
{
  home.username = "agent";
  home.homeDirectory = "/home/agent";
  home.stateVersion = "26.05";

  targets.genericLinux.enable = false;

  home.packages = toolchain;

  # The claude native installer puts its binary here, and cannot add it to PATH
  # itself: home-manager owns .zshrc as a read-only store symlink.
  home.sessionPath = [ "${config.home.homeDirectory}/.local/bin" ];

  # Points at this user's own rootless daemon. Set per-user rather than through
  # `virtualisation.docker.rootless.setSocketVariable`, which would export it
  # for max too -- see nix/nixos/pc/agent-user.nix.
  home.sessionVariables.DOCKER_HOST =
    "unix:///run/user/${toString osConfig.users.users.agent.uid}/docker.sock";

  # Minimal on purpose: `ssh agent@pc <cmd>` runs a non-login zsh, which reads
  # .zshenv and nothing else -- that is where home-manager puts the session
  # variables and PATH above.
  programs.zsh.enable = true;

  programs.git = {
    enable = true;
    settings = {
      # Worker commits are attributable in `git log` as the bot account, not as
      # max. There is no GitHub credential here; this is identity, not access.
      user.name = "MaxWolf-01-clanker";
      user.email = "MaxWolf-01-clanker@users.noreply.github.com";
      init.defaultBranch = "master";
      push.default = "current";
      pull.rebase = false;
    };
  };

  # No resurrect, no clipboard integration: worker sessions are ephemeral and
  # this machine is headless. Just enough that attaching to watch a worker
  # feels like max's own tmux.
  programs.tmux = {
    enable = true;
    prefix = "C-a";
    escapeTime = 0;
    historyLimit = 50000;
    baseIndex = 1;
    mouse = true;
    keyMode = "vi";
    extraConfig = ''
      set -g default-terminal "tmux-256color"
      set -g renumber-windows on
      set -g status-style "bg=colour235,fg=colour250"
      set -g status-left "#[fg=colour117,bold] #S #[fg=colour244]| "
    '';
  };

  # What dispatch reads before planning a wave. The toolchain list is generated
  # from the packages above, so that half cannot drift; the limits below are
  # claims about this host, and every one of them has been exercised.
  home.file."HOST.md".text = ''
    ---
    host: pc
    user: agent
    isolated: true
    ---

    # Worker host: agent@pc

    Unattended workers run here as `agent`. Generated by that user's Home
    Manager config (`nix/home/hosts/pc-agent.nix` in ~/.dotfiles).

    ## Available

    ${lib.concatStringsSep " " (map (c: "`${c}`") (lib.sort lib.lessThan (map (p: p.meta.mainProgram) toolchain)))}, plus `nix` with
    flakes so a project's own `nix develop` works, rootless `docker` confined
    to this user, `claude` with the `mx` plugin, and the public internet.
    Anything else a project needs comes from its own setup target, inside the
    worktree.

    ## Belongs elsewhere

    - **Work needing GitHub.** No credentials here: `gh` is unauthenticated and
      nothing can push or open a PR. History arrives by push from the
      orchestrator and leaves the same way.
    - **Work needing the GPU.** Nothing stops you using it, and that is the
      point: it is spoken for by this machine's own workers, so a ticket that
      wants it goes back rather than running here.
    - **Work needing another machine on the network.** Only the orchestrator's
      side can reach one.
    - **Driving a real browser.** Headless renders work; a session you can
      click does not.
  '';
}
