#!/bin/bash

alias preflect="echo First think deeply, reviewing and then interview me, one question at a time presenting me well-considered options and suggestions to advance your clarity until your reach 100% clarity. For each question try to indicate what the source of confusion might be, or how answering this will determine something you need (be concise). Try to opt for multiple-choice when it is clear enough to do so".
alias pprsummary="echo Please create a concise summary of the *net* changes that are introduced in this branch / PR. Don't look at individual commit or commit messsages, just the diff this PR introduces. A good PR description mentions core features added, and changes to existing models/api/... or dev experience, if applicable."
alias ppaperclipper="echo Please extract the full text from this paper, including appendices, math formulas in LaTeX, and the content of all tables. Also include captions for figures and tables (but do not try to describe figures unless specifically asked to do so). Omit metadata, in-text citations, and the reference list. If you are claude web, create an artefact."

