source ~/.aliases
source ~/.colors
source ~/.exports
source ~/.functions
source ~/.plugins
source ~/.zsh_config
if [ -f ~/.dotfiles/secrets/zshrc ]; then source ~/.dotfiles/secrets/zshrc; fi
source ~/.dotfiles/zsh/plugin-files/mytheme.zsh-theme
wal --theme base16-atelier-cave &> /dev/null

# disable terminal flow control (can press ctrl+s without freezing it)
stty -ixon

# pressing "`" once suffices for the key to be printed 
setxkbmap de nodeadkeys &> /dev/null

# fuzzy search with Ctrl + R | https://github.com/junegunn/fzf | Get's automatically appended here if not present
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


# $HOMe also not recognized? Maybe add a script in bootstrap which sed replaced $(echo $HOME) or sth lol; Keep in mind it needs to be idempotent though.
# Tilde does not get expanded within quotes -> $HOME
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/max/miniforge3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/max/miniforge3/etc/profile.d/conda.sh" ]; then
        . "/home/max/miniforge3/etc/profile.d/conda.sh"
    else
        export PATH="/home/max/miniforge3/bin:$PATH"
    fi
fi
unset __conda_setup

if [ -f "/home/max/miniforge3/etc/profile.d/mamba.sh" ]; then
    . "/home/max/miniforge3/etc/profile.d/mamba.sh"
fi
# <<< conda initialize <<<

# bun completions
[ -s "/home/max/.bun/_bun" ] && source "/home/max/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
