# zmodload zsh/zprof
source ~/.aliases
source ~/.exports
source ~/.functions
source ~/.plugins
source ~/.zsh_config
if [ -f ~/.dotfiles/secrets/zshrc ]; then source ~/.dotfiles/secrets/zshrc; fi
source ~/.dotfiles/zsh/plugin-files/mytheme.zsh-theme
source ~/.dotfiles/zsh/wal-theme-config.zsh

# disable terminal flow control (can press ctrl+s without freezing it)
stty -ixon

# pressing "`" once suffices for the key to be printed 
setxkbmap de nodeadkeys &> /dev/null

# fuzzy search with Ctrl + R | https://github.com/junegunn/fzf | Get's automatically appended here if not present
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# clipse tui clipboard manager
if command -v clipse &> /dev/null; then
  clipse --listen
fi

# bun completions
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

eval "$(zoxide init zsh)"
