source ~/.aliases
source ~/.colors
source ~/.exports
source ~/.functions
source ~/.plugins
source ~/.zsh_config
source zsh/plugin-files/jovial.zsh-theme

# fuzzy search with Ctrl + R | https://github.com/junegunn/fzf | Get's automatically appended here if not present
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


# Tilde does not get expanded within quotes -> $HOME
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('$HOME/miniconda/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/miniconda/etc/profile.d/conda.sh" ]; then
        . "$HOME/miniconda/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/miniconda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

