name: Update flake.lock
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # daily 3am

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/update-flake-lock@v28
        with:
          branch: flake-update
          commit-msg: "flake.lock: update"
          pr-title: "flake.lock: update"
          pr-body: |
            Automated weekly flake.lock update.
            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```
