# Named display layouts. Format and commands: display-layout --help

[aliases]
hp = {vendor = "HPN", product = "HP M27fwa FHD"}
arzopa = {vendor = "GWD", product = "ARZOPA"}
laptop = {vendor = "AUO", product = "0xc199"}

[layouts.desk-tall]
arzopa = {x = 0, y = 220, mode = "2560x1600@59.997", scale = 1.3333333730697632, transform = "90"}
hp = {x = 1200, y = 0, mode = "1920x1080@60.000"}
laptop = {x = 1200, y = 1080, mode = "2560x1600@165.040", scale = 1.3333333730697632, primary = true}
